### ISSUE TITLE
Add the ability to pass through cookies?

### ISSUE THREAD

**Issue by JBKahn** [eofs/django-rest-framework-proxy#11]
In order to interface this with a system that uses headers for auth and a system that uses cookies for auth I had to copy the definition of `proxy` into the View we are inheriting from and modify it so that it had something like:

```python
def proxy(self, request, *args, **kwargs):
    # top of function
    cookies = self.get_request_cookies(request)
    # wrapped try/except call
    request(
        request.method
        url,
        params=params,
        data=body,
        headers=headers
        timeout=self.proxy_settings.TIMEOUT,
        verify=verify_ssl,
        cookies=cookies
    )
def get_request_cookies(self, request):
    return None
```
And then I just override `get_request_cookies` in the view.

Is there a style/way that I could add the ability to send cookies through? I'd be happy to write the code. Currently, I don't want to send a cookie from the original request, but I want to attach a cookie to be sent to the proxy host. I'm not sure what this package should do by default if the ability to specify cookies is added.

**Comment by eofs** [comment]
Hi @JBKahn !

The way you temporary implemented the solution looks good! I think that passing all original cookies by default is not really a good solution as it might leak confidential user data to 3rd-party servers. That's actually the reason why `get_default_headers` passes only `Accept`, `Accept-Language` and `Content-Length` headers.

It would be really great if you could send  Pull Request :+1:

**Comment by JBKahn** [comment]
PR sent!

**Comment by JBKahn** [comment]
I'm pushing out the code that uses this today, any chance you can get the new version up on pypi?

**Comment by eofs** [comment]
Uploaded! :)

**Comment by JBKahn** [comment]
Thanks!
