### ISSUE TITLE
request.QUERY_PARAMS and request.DATA deprecated

### ISSUE THREAD

**Issue by abjorshammar** [eofs/django-rest-framework-proxy#13]
Installed without previously having django-rest-framework installed, this pulled in the latest version (3.2.4). This gave errors about [`request.QUERY_PARAMS`](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/request.py#L378) and [`request.DATA`](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/request.py#L362) being deprecated.

I checked the code, and replacing your calls to these functions with lowercase names seems to work.
[`request.QUERY_PARAMS -> request.query_params`](https://github.com/eofs/django-rest-framework-proxy/blob/master/rest_framework_proxy/views.py#L48)
[`request.DATA -> request.data`](https://github.com/eofs/django-rest-framework-proxy/blob/master/rest_framework_proxy/views.py#L58)

I would send you a pull request, but I don't quite understand what you are doing here, and I don't want to break some logic going on:
[`return request.DATA if request.DATA else request.data`](https://github.com/eofs/django-rest-framework-proxy/blob/master/rest_framework_proxy/views.py#L59)

The earliest relase that works with the lowercase names seems to be 3.0.1, if you want to update the requirements.

**Comment by eofs** [comment]
Hi @abjorshammar 

That might be there to support both old `DATA` and new `data` attributes. I don't see any reason why it shouldn't work if you just replace it with the lowercase version and if we raise the minimum requirement.

Throw me a PR and I'll merge it :)

**Comment by eofs** [comment]
Closed by c80e7e4aa13685e6b6ca8b6c32022cd8df0fa13d
