### ISSUE TITLE
ImportError: No module named packages.urllib3.response

### ISSUE THREAD

**Issue by daluege** [eofs/django-rest-framework-proxy#15]
ImportError in rest_framework_proxy/adapters.py, line 4:

    No module named packages.urllib3.response

See also https://github.com/locustio/locust/issues/148

**Comment by eofs** [comment]
Hi @daluege,

It seems that the debian's package maintainer has removed the patch. I've not tested it but you can try to check if it works now.

Usually it's good practice to use virtualenv to manage your project dependencies as with it you can use different versions of packages throughout your projects and you don't have to rely on your distribution's packages.
